#!/bin/bash
export CWC_LOG_DIR=/data/cwc_integ_service/session_logs/
python3 cwc_integ_app.py reset
nohup gunicorn -w 1 -t 600 -b 0.0.0.0:8080 cwc_integ_app:app --access-logfile 'service_logs/access.log' --log-file 'service_logs/server.log' &>> 'service_logs/app.log' &
nohup python3 cwc_integ_app.py monitor &>> service_logs/monitor.log &
